server:
  port: 8083

spring:
  application:
    name: match-service

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080

db-service:
  url: http://db-service:8082
